task: review-code
description: Review code for quality and best practices
instructions: |
  1. Check code style and consistency
  2. Verify functionality and logic correctness
  3. Assess test coverage and quality
  4. Apply {{ ref:./krci-ai/data/best-practices.md }} guidelines
  5. Suggest specific improvements with rationale
  6. Format review using {{ ref:./krci-ai/templates/code-review.md }}
