style: github
template: CHANGELOG.tpl.md
info:
  title: KubeRocketAI CLI Changelog
  repository_url: https://github.com/KubeRocketCI/kuberocketai
options:
  commits:
    filters:
      Type:
        - feat
        - fix
        - perf
        - refactor
        - docs
        - style
        - test
        - chore
  commit_groups:
    title_maps:
      feat: Features
      fix: Bug Fixes
      perf: Performance Improvements
      refactor: Code Refactoring
      docs: Documentation
      style: Styles
      test: Tests
      chore: Chores
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE