name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

env:
  GO_VERSION: "1.24.4"

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Cache development tools
        uses: actions/cache@v5
        with:
          path: bin/
          key: ${{ runner.os }}-tools-${{ hashFiles('Makefile') }}
          restore-keys: |
            ${{ runner.os }}-tools-

      - name: Install development tools
        run: make tools

      - name: Run CI pipeline
        run: make ci

      - name: Generate coverage report
        run: make test-coverage

      - name: Upload coverage reports
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.out
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false

  build-cross-platform:
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true


      - name: Build all platforms
        run: make build-all

      - name: Test Linux binary
        run: |
          chmod +x dist/krci-ai-linux-amd64
          ./dist/krci-ai-linux-amd64 --version
          ./dist/krci-ai-linux-amd64 --help

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: krci-ai-binaries
          path: dist/
