name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

env:
  GO_VERSION: "1.24.4"

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Install development tools
        run: make tools

      - name: Run CI pipeline
        run: make ci

      - name: Generate coverage report
        run: make test-coverage

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v6.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build-cross-platform:
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Build all platforms
        run: make build-all

      - name: Test Linux binary
        run: |
          chmod +x dist/krci-ai-linux-amd64
          ./dist/krci-ai-linux-amd64 --version
          ./dist/krci-ai-linux-amd64 --help

      - name: Install full framework with built binary
        run: |
          chmod +x dist/krci-ai-linux-amd64
          ./dist/krci-ai-linux-amd64 install --all --force

      - name: Run validation with built binary
        run: |
          ./dist/krci-ai-linux-amd64 validate

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: krci-ai-binaries
          path: dist/

  test-windows:
    runs-on: windows-latest
    needs: build-cross-platform

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: krci-ai-binaries
          path: dist/

      - name: Test Windows binary
        run: |
          .\dist\krci-ai-windows-amd64.exe --version
          .\dist\krci-ai-windows-amd64.exe --help

      - name: Install full framework with built binary
        run: .\dist\krci-ai-windows-amd64.exe install --all --force

      - name: Run commans for testing
        run: |
          .\dist\krci-ai-windows-amd64.exe install --ide cursor --force
          .\dist\krci-ai-windows-amd64.exe install --ide claude --force
          .\dist\krci-ai-windows-amd64.exe install --ide vscode --force
          .\dist\krci-ai-windows-amd64.exe list agents
          .\dist\krci-ai-windows-amd64.exe tokens --all
          .\dist\krci-ai-windows-amd64.exe bundle --agent pm
          .\dist\krci-ai-windows-amd64.exe validate
